ScheduleAnalyzer/Components/ChangePasswordViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScheduleAnalyzer.Data;
using ScheduleAnalyzer.Models;
using ScheduleAnalyzer.Models.SA_Models.ViewModels;

namespace ScheduleAnalyzer.Components
{
    public class ChangePasswordViewComponent : ViewComponent
    {
        protected ApplicationDbContext db => (ApplicationDbContext)HttpContext.RequestServices.GetService(typeof(ApplicationDbContext));

        public IViewComponentResult Invoke()
        {
            ChangePassViewModel vm = new ChangePassViewModel();
            vm.User = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name) as ApplicationUser;
            return View(vm);
        }
    }
}

ScheduleAnalyzer/Components/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScheduleAnalyzer.Data;
using ScheduleAnalyzer.Models;
using ScheduleAnalyzer.Models.SA_Models.ViewModels;

namespace ScheduleAnalyzer.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        protected ApplicationDbContext db => (ApplicationDbContext)HttpContext.RequestServices.GetService(typeof(ApplicationDbContext));

        public IViewComponentResult Invoke()
        {
            NavBarViewModel vm = new NavBarViewModel();
            vm.User = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name) as ApplicationUser;
            return View(vm);
        }
    }
}

ScheduleAnalyzer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ScheduleAnalyzer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/bootstrap_theme/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert/dist/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/css/maincss/main.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header>
        @await Component.InvokeAsync("Navigation")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("ChangePassword")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ScheduleAnalyzer/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Schedule Analyzer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/bootstrap_theme/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/logincss/login.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>